"""add title_en to media

Revision ID: 3513f0d57b2d
Revises: f0bece602f6a
Create Date: 2025-08-16 17:07:38.725959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3513f0d57b2d'
down_revision: Union[str, Sequence[str], None] = 'f0bece602f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('title_en', sa.String(), nullable=True))
    op.create_index(op.f('ix_media_title_en'), 'media', ['title_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_title_en'), table_name='media')
    op.drop_column('media', 'title_en')
    # ### end Alembic commands ###
