"""update media status enum to ukrainian

Revision ID: f0bece602f6a
Revises: 8ad289eed652
Create Date: 2025-08-09 13:59:21.830823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bece602f6a'
down_revision: Union[str, Sequence[str], None] = '8ad289eed652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE mediastatus ADD VALUE IF NOT EXISTS 'заплановано'")
    op.execute("ALTER TYPE mediastatus ADD VALUE IF NOT EXISTS 'переглядаю'")
    op.execute("ALTER TYPE mediastatus ADD VALUE IF NOT EXISTS 'переглянуто'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
